import "dotenv/config";
import { connectDB } from "../config/db.js";
import MenuItem from "../models/MenuItem.js";
import { ensureMenuEmbeddings } from "../services/ragService.js";

const dishes = [
  // --- Original 6 Dishes ---
  {
    name: "Paneer Tikka Bowl",
    description: "Grilled cottage cheese marinated in spiced yogurt, served over quinoa with roasted peppers.",
    category: "Main Course",
    dietType: "veg",
    price: 249,
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7",
    ingredients: ["paneer", "yogurt", "quinoa", "bell pepper", "spices"],
    allergens: ["dairy"],
    spiceLevel: 2,
    prepTimeMinutes: 20,
    nutrition: { calories: 420, protein_g: 28, carbs_g: 38, fat_g: 16, fiber_g: 6, sugar_g: 5, sodium_mg: 480 },
    healthTags: ["high-protein", "diabetic-friendly"],
    rating: 4.5,
  },
  {
    name: "Grilled Chicken Salad",
    description: "Lean grilled chicken breast over mixed greens with a light lemon vinaigrette.",
    category: "Salads",
    dietType: "non-veg",
    price: 279,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    ingredients: ["chicken breast", "lettuce", "cherry tomato", "cucumber", "olive oil"],
    allergens: [],
    spiceLevel: 0,
    prepTimeMinutes: 15,
    nutrition: { calories: 320, protein_g: 38, carbs_g: 12, fat_g: 12, fiber_g: 4, sugar_g: 3, sodium_mg: 350 },
    healthTags: ["high-protein", "low-calorie", "weight-loss"],
    rating: 4.6,
  },
  {
    name: "Butter Chicken",
    description: "Classic creamy tomato-based curry with tender chicken, served with rice.",
    category: "Main Course",
    dietType: "non-veg",
    price: 320,
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398",
    ingredients: ["chicken", "butter", "tomato", "cream", "rice"],
    allergens: ["dairy"],
    spiceLevel: 1,
    prepTimeMinutes: 25,
    nutrition: { calories: 680, protein_g: 32, carbs_g: 52, fat_g: 38, fiber_g: 3, sugar_g: 8, sodium_mg: 920 },
    healthTags: [],
    rating: 4.7,
  },
  {
    name: "Vegan Buddha Bowl",
    description: "Roasted sweet potato, chickpeas, avocado and kale with a tahini dressing.",
    category: "Bowls",
    dietType: "vegan",
    price: 260,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    ingredients: ["sweet potato", "chickpeas", "avocado", "kale", "tahini"],
    allergens: ["sesame"],
    spiceLevel: 0,
    prepTimeMinutes: 18,
    nutrition: { calories: 410, protein_g: 14, carbs_g: 48, fat_g: 18, fiber_g: 12, sugar_g: 9, sodium_mg: 300 },
    healthTags: ["low-calorie", "high-fiber", "diabetic-friendly"],
    rating: 4.4,
  },
  {
    name: "Chocolate Brownie",
    description: "Rich fudgy brownie topped with a scoop of vanilla ice cream.",
    category: "Dessert",
    dietType: "veg",
    price: 180,
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c",
    ingredients: ["chocolate", "flour", "butter", "sugar", "egg"],
    allergens: ["gluten", "dairy", "egg"],
    spiceLevel: 0,
    prepTimeMinutes: 10,
    nutrition: { calories: 540, protein_g: 6, carbs_g: 62, fat_g: 30, fiber_g: 3, sugar_g: 44, sodium_mg: 180 },
    healthTags: [],
    rating: 4.8,
  },
  {
    name: "High-Protein Sprout Salad",
    description: "Sprouted moong and chickpeas tossed with onion, tomato, and a citrus dressing.",
    category: "Salads",
    dietType: "vegan",
    price: 160,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    ingredients: ["sprouted moong", "chickpeas", "onion", "tomato", "lemon"],
    allergens: [],
    spiceLevel: 1,
    prepTimeMinutes: 10,
    nutrition: { calories: 220, protein_g: 16, carbs_g: 30, fat_g: 4, fiber_g: 9, sugar_g: 4, sodium_mg: 210 },
    healthTags: ["high-protein", "low-calorie", "diabetic-friendly", "weight-loss"],
    rating: 4.3,
  },

  // --- 15 New Dishes ---
  {
    name: "Quinoa Veggie Wrap",
    description: "Whole wheat wrap filled with seasoned quinoa, black beans, corn, and fresh salsa.",
    category: "Wraps",
    dietType: "vegan",
    price: 199,
    imageUrl: "https://images.unsplash.com/photo-1528736235302-52922df5c122",
    ingredients: ["whole wheat tortilla", "quinoa", "black beans", "corn", "salsa"],
    allergens: ["gluten"],
    spiceLevel: 1,
    prepTimeMinutes: 12,
    nutrition: { calories: 310, protein_g: 12, carbs_g: 40, fat_g: 10, fiber_g: 8, sugar_g: 4, sodium_mg: 320 },
    healthTags: ["high-fiber", "low-calorie"],
    rating: 4.2,
  },
  {
    name: "Mutton Dum Biryani",
    description: "Fragrant basmati rice slow-cooked with tender mutton pieces and whole spices.",
    category: "Main Course",
    dietType: "non-veg",
    price: 399,
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8",
    ingredients: ["mutton", "basmati rice", "ghee", "yogurt", "biryani spices", "fried onions"],
    allergens: ["dairy"],
    spiceLevel: 2,
    prepTimeMinutes: 45,
    nutrition: { calories: 750, protein_g: 40, carbs_g: 65, fat_g: 35, fiber_g: 4, sugar_g: 2, sodium_mg: 850 },
    healthTags: ["high-protein"],
    rating: 4.9,
  },
  {
    name: "Keto Lemon Herb Fish",
    description: "Pan-seared white fish fillet with lemon, herbs, and garlic butter asparagus.",
    category: "Main Course",
    dietType: "non-veg",
    price: 349,
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
    ingredients: ["white fish", "asparagus", "lemon", "butter", "garlic", "herbs"],
    allergens: ["fish", "dairy"],
    spiceLevel: 0,
    prepTimeMinutes: 20,
    nutrition: { calories: 280, protein_g: 35, carbs_g: 5, fat_g: 12, fiber_g: 2, sugar_g: 1, sodium_mg: 400 },
    healthTags: ["keto", "high-protein", "low-carb", "weight-loss"],
    rating: 4.6,
  },
  {
    name: "Berry Oat Smoothie",
    description: "A thick, creamy blend of mixed berries, rolled oats, and almond milk.",
    category: "Beverages",
    dietType: "vegan",
    price: 149,
    imageUrl: "https://images.unsplash.com/photo-1556881286-fc6915169721",
    ingredients: ["mixed berries", "oats", "almond milk", "chia seeds", "maple syrup"],
    allergens: ["nuts"],
    spiceLevel: 0,
    prepTimeMinutes: 5,
    nutrition: { calories: 240, protein_g: 8, carbs_g: 42, fat_g: 4, fiber_g: 10, sugar_g: 14, sodium_mg: 120 },
    healthTags: ["high-fiber", "low-calorie"],
    rating: 4.5,
  },
  {
    name: "Teriyaki Tofu Stir-Fry",
    description: "Crispy tofu cubes tossed in a sweet and savory teriyaki sauce with broccoli and bell peppers.",
    category: "Main Course",
    dietType: "vegan",
    price: 229,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    ingredients: ["tofu", "broccoli", "bell pepper", "soy sauce", "ginger", "sesame seeds"],
    allergens: ["soy", "sesame"],
    spiceLevel: 1,
    prepTimeMinutes: 20,
    nutrition: { calories: 320, protein_g: 22, carbs_g: 25, fat_g: 14, fiber_g: 6, sugar_g: 10, sodium_mg: 580 },
    healthTags: ["high-protein", "vegan"],
    rating: 4.3,
  },
  {
    name: "Dal Tadka & Jeera Rice",
    description: "Comforting yellow lentils tempered with cumin, garlic, and ghee, served with cumin rice.",
    category: "Main Course",
    dietType: "veg",
    price: 189,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d",
    ingredients: ["yellow lentils", "basmati rice", "cumin", "garlic", "ghee", "tomato"],
    allergens: ["dairy"],
    spiceLevel: 1,
    prepTimeMinutes: 25,
    nutrition: { calories: 450, protein_g: 18, carbs_g: 60, fat_g: 15, fiber_g: 12, sugar_g: 3, sodium_mg: 460 },
    healthTags: ["high-fiber", "vegetarian"],
    rating: 4.7,
  },
  {
    name: "Creamy Mushroom Risotto",
    description: "Arborio rice cooked slowly in vegetable broth, finished with parmesan and wild mushrooms.",
    category: "Main Course",
    dietType: "veg",
    price: 310,
    imageUrl: "https://images.unsplash.com/photo-1633337474581-2296d9f78330",
    ingredients: ["arborio rice", "mushrooms", "vegetable broth", "parmesan cheese", "butter", "garlic"],
    allergens: ["dairy"],
    spiceLevel: 0,
    prepTimeMinutes: 30,
    nutrition: { calories: 520, protein_g: 12, carbs_g: 58, fat_g: 24, fiber_g: 4, sugar_g: 2, sodium_mg: 610 },
    healthTags: [],
    rating: 4.6,
  },
  {
    name: "Greek Yogurt Berry Parfait",
    description: "Layers of thick Greek yogurt, homemade granola, and fresh strawberries.",
    category: "Dessert",
    dietType: "veg",
    price: 170,
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777",
    ingredients: ["greek yogurt", "granola", "strawberries", "honey"],
    allergens: ["dairy", "gluten", "nuts"],
    spiceLevel: 0,
    prepTimeMinutes: 5,
    nutrition: { calories: 210, protein_g: 15, carbs_g: 25, fat_g: 5, fiber_g: 3, sugar_g: 15, sodium_mg: 85 },
    healthTags: ["high-protein", "low-calorie"],
    rating: 4.8,
  },
  {
    name: "Zucchini Pesto Pasta",
    description: "Spiralized zucchini noodles tossed in a fresh basil and walnut pesto.",
    category: "Main Course",
    dietType: "vegan",
    price: 250,
    imageUrl: "https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4",
    ingredients: ["zucchini", "basil", "walnuts", "olive oil", "garlic", "nutritional yeast"],
    allergens: ["nuts"],
    spiceLevel: 0,
    prepTimeMinutes: 15,
    nutrition: { calories: 290, protein_g: 8, carbs_g: 12, fat_g: 22, fiber_g: 4, sugar_g: 5, sodium_mg: 210 },
    healthTags: ["keto", "low-carb", "weight-loss", "vegan"],
    rating: 4.4,
  },
  {
    name: "Masala Omelette",
    description: "Fluffy three-egg omelette with diced onions, tomatoes, green chilies, and fresh coriander.",
    category: "Breakfast",
    dietType: "non-veg",
    price: 120,
    imageUrl: "https://images.unsplash.com/photo-1510693062532-6014467d1db0",
    ingredients: ["eggs", "onion", "tomato", "green chili", "coriander", "oil"],
    allergens: ["egg"],
    spiceLevel: 2,
    prepTimeMinutes: 10,
    nutrition: { calories: 260, protein_g: 18, carbs_g: 4, fat_g: 18, fiber_g: 1, sugar_g: 2, sodium_mg: 380 },
    healthTags: ["keto", "high-protein", "low-carb"],
    rating: 4.5,
  },
  {
    name: "Baked Salmon & Quinoa",
    description: "Oven-baked salmon fillet brushed with soy-ginger glaze, served with fluffy quinoa.",
    category: "Main Course",
    dietType: "non-veg",
    price: 550,
    imageUrl: "https://images.unsplash.com/photo-1485921325833-c519f76c4927",
    ingredients: ["salmon", "quinoa", "soy sauce", "ginger", "honey", "olive oil"],
    allergens: ["fish", "soy"],
    spiceLevel: 0,
    prepTimeMinutes: 25,
    nutrition: { calories: 380, protein_g: 42, carbs_g: 28, fat_g: 12, fiber_g: 4, sugar_g: 5, sodium_mg: 450 },
    healthTags: ["high-protein", "pescatarian"],
    rating: 4.9,
  },
  {
    name: "Palak Paneer",
    description: "Soft cottage cheese cubes in a smooth, spiced spinach gravy.",
    category: "Main Course",
    dietType: "veg",
    price: 260,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    ingredients: ["spinach", "paneer", "onion", "tomato", "garlic", "cream"],
    allergens: ["dairy"],
    spiceLevel: 1,
    prepTimeMinutes: 25,
    nutrition: { calories: 390, protein_g: 20, carbs_g: 15, fat_g: 28, fiber_g: 5, sugar_g: 3, sodium_mg: 410 },
    healthTags: ["keto", "vegetarian"],
    rating: 4.7,
  },
  {
    name: "Mediterranean Chickpea Salad",
    description: "Refreshing salad with chickpeas, cucumbers, kalamata olives, feta, and red onion.",
    category: "Salads",
    dietType: "veg",
    price: 240,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999",
    ingredients: ["chickpeas", "cucumber", "olives", "feta cheese", "red onion", "olive oil"],
    allergens: ["dairy"],
    spiceLevel: 0,
    prepTimeMinutes: 10,
    nutrition: { calories: 280, protein_g: 10, carbs_g: 30, fat_g: 14, fiber_g: 8, sugar_g: 4, sodium_mg: 520 },
    healthTags: ["high-fiber", "vegetarian", "diabetic-friendly"],
    rating: 4.5,
  },
  {
    name: "Coconut Chia Pudding",
    description: "Chia seeds soaked overnight in coconut milk, topped with mango puree.",
    category: "Dessert",
    dietType: "vegan",
    price: 190,
    imageUrl: "https://images.unsplash.com/photo-1490474418585-ba9f52fce1cb",
    ingredients: ["chia seeds", "coconut milk", "mango", "maple syrup"],
    allergens: [],
    spiceLevel: 0,
    prepTimeMinutes: 5,
    nutrition: { calories: 230, protein_g: 6, carbs_g: 22, fat_g: 12, fiber_g: 10, sugar_g: 12, sodium_mg: 45 },
    healthTags: ["high-fiber", "vegan", "dairy-free"],
    rating: 4.6,
  },
  {
    name: "Spicy Chicken Tikka Wrap",
    description: "Tandoori chicken pieces wrapped in a whole wheat flatbread with mint chutney and onions.",
    category: "Wraps",
    dietType: "non-veg",
    price: 210,
    imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f",
    ingredients: ["chicken", "whole wheat roti", "yogurt", "mint", "onion", "tikka spices"],
    allergens: ["gluten", "dairy"],
    spiceLevel: 3,
    prepTimeMinutes: 15,
    nutrition: { calories: 410, protein_g: 28, carbs_g: 35, fat_g: 16, fiber_g: 5, sugar_g: 3, sodium_mg: 550 },
    healthTags: ["high-protein"],
    rating: 4.7,
  }
];

async function run() {
  await connectDB();
  await MenuItem.deleteMany({});
  await MenuItem.insertMany(dishes);
  console.log(`Seeded ${dishes.length} dishes.`);

  console.log("Generating embeddings for RAG (requires OPENAI_API_KEY)...");
  const count = await ensureMenuEmbeddings();
  console.log(`Embedded ${count} dishes.`);

  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});